version: '3.4'

services:
  algdataapigateway:
    image: ${DOCKER_REGISTRY-}algdataapigateway
    build:
      context: .
      dockerfile: AlgDataAPI/Dockerfile

  algorithms.api:
    image: ${DOCKER_REGISTRY-}algorithmsapi
    build:
      context: .
      dockerfile: Algorithms.API/Dockerfile


  datastructure.api:
    image: ${DOCKER_REGISTRY-}datastructureapi
    build:
      context: .
      dockerfile: DataStructure.API/Dockerfile


  calculationhostedservice:
    image: ${DOCKER_REGISTRY-}calculationhostedservice
    build:
      context: .
      dockerfile: CalculationHostedService/Dockerfile

  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    ports:
        - "5672:5672"
        - "15672:15672"